# Workflow inspired by Kirill MÃ¼ller from cynkra (https://github.com/cynkra)

on:
  # daily run (midnight BC time)
  schedule:
  - cron: "0 8 * * *"

name: fledge


permissions:
  contents: write

jobs:
  fledge:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure git
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install packages
        run: |
          install.packages(c("remotes"))
          remotes::install_github("cynkra/fledge")
        shell: Rscript {0}

      - name: Bump version
        run: |
          fledge::bump_version(which = "dev", no_change_behavior = "noop")
          fledge::finalize_version(push = TRUE)
        shell: Rscript {0}
